version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: talentforge-backend-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - talentforge-network

networks:
  talentforge-network:
    driver: bridge
