import { Router } from 'express';
import healthRoutes from '../modules/health/health.module.js';
import authRoutes from '../modules/auth/auth.module.js';
import companyRoutes from '../modules/company/company.module.js';
import jobRoutes from '../modules/jobs/routes/jobs.routes.js';
import candidateRoutes from '../modules/candidate/routes/candidate.routes.js';
import candidatesRoutes from '../modules/candidate/routes/candidates.routes.js';
import applicationRoutes from '../modules/application/routes/application.C.routes.js';
import recruiterApplicationRoutes from '../modules/application/routes/application.R.routes.js';
import hiringWorkflowRoutes from '../modules/hiring-workflow/routes/stage-library.routes.js';
import workflowRoutes from '../modules/hiring-workflow/routes/workflow.routes.js';
import applicationWorkflowRoutes from '../modules/hiring-workflow/routes/application-workflow.routes.js';
import questionRoutes from '../modules/assessment/routes/question.routes.js';
import assessmentRoutes from '../modules/assessment/routes/assessmentBuilder..routes.js';
import assessmentAssignmentRoutes from '../modules/assessment/routes/assessmentAssignment.routes.js';
import assessmentAttemptRoutes from '../modules/assessment/routes/candidateAssessment.routes.js';
import assessmentEvaluationRoutes from '../modules/assessment/routes/assessmentEvaluation.routes.js';
import atsIntegrationRoutes from '../modules/assessment/routes/atsIntegration.routes.js';
import interviewsRoutes from '../modules/interviews/routes/interviews.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use("/companies", companyRoutes);
router.use("/jobs", jobRoutes);
router.use("/assessments/assignments", assessmentAssignmentRoutes);
router.use("/assessment-attempts", assessmentAttemptRoutes);
router.use("/assessment/evaluation", assessmentEvaluationRoutes);
router.use("/assessment/applications", atsIntegrationRoutes);
router.use("/candidate", candidateRoutes);
router.use("/candidates", candidatesRoutes);
router.use("/candidate/applications", applicationRoutes);
router.use("/employer/applications", recruiterApplicationRoutes);
router.use("/hiring-workflow/stage-library", hiringWorkflowRoutes);
router.use("/hiring-workflow", workflowRoutes);
router.use("/hiring-workflow/applications", applicationWorkflowRoutes);
router.use("/questions", questionRoutes);
router.use("/assessments", assessmentRoutes);
router.use("/interviews", interviewsRoutes);

export default router;
