export const candidateSelect = {
    id: true,
    userId: true,
    fullName: true,
    createdAt: true,
    updatedAt: true,
} as const;

export const candidateProfileSelect = {
    id: true,
    userId: true,
    fullName: true,
    phone: true,
    profilePicture: true,
    headline: true,
    bio: true,
    gender: true,
    experienceLevel: true,
    currentLocation: true,
    preferredLocation: true,
    currentCompany: true,
    currentDesignation: true,
    totalExperience: true,
    expectedSalary: true,
    currentSalary: true,
    noticePeriod: true,
    linkedinUrl: true,
    githubUrl: true,
    portfolioUrl: true,
    websiteUrl: true,
    isOpenToWork: true,
    profileCompleted: true,
    createdAt: true,
    updatedAt: true,
};