export const companySelect = {
    id: true,
    companyName: true,
    slug: true,
    companyEmail: true,
    phoneNumber: true,
    website: true,
    logo: true,
    coverImage: true,
    description: true,
    industry: true,
    companySize: true,
    foundedYear: true,
    headquarters: true,
    linkedinUrl: true,
    twitterUrl: true,
    isVerified: true,
    createdAt: true,
    updatedAt: true,
} as const;