export const recruiterSelect = {
    id: true,
    userId: true,
    companyId: true,
    firstName: true,
    lastName: true,
    phone: true,
    designation: true,
    department: true,
    profilePicture: true,
    linkedinUrl: true,
    isPrimaryRecruiter: true,
    canCreateJobs: true,
    canEditJobs: true,
    canDeleteJobs: true,
    canScheduleInterview: true,
    isActive: true,
    createdAt: true,
    updatedAt: true,
} as const;